version: '3.9'

services:
  api:
    build: .
    container_name: taskmaster_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: taskmaster_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: taskmaster_redis
    ports:
      - "6379:6379"

  worker:
    build: .
    container_name: taskmaster_worker
    command: celery -A celery_worker.celery worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:

  beat:
    build: .
    container_name: taskmaster_beat
    command: celery -A celery_worker.celery beat --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis
      - db
    env_file:
      - .env
